---
- hosts: all
  tasks:
  - name: Install dependencies
    ansible.builtin.apt:
      pkg:
      - apache2
      - ghostscript
      - libapache2-mod-php
      - mysql-server
      - php
      - php-bcmath
      - php-curl
      - php-imagick
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - php-xml
      - php-zip
      state: latest
      update_cache: yes
    become: yes

  - name: Create the installation directory
    ansible.builtin.file:
      path: /srv/www
      state: directory
      owner: www-data
      mode: '0755'
    become: yes

  - name: Download and Unarchive a wordpress file
    ansible.builtin.unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /srv/www
      remote_src: yes
    become: yes
